### ISSUE TITLE
  Target class [Flobbos\Pagebuilder\Database\Seeds\ElementTableSeeder] does not exist.

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [Flobbos/laravel-pagebuilder#21]
After run php artisan pagebuilder:install command i faced this error  Target class [Flobbos\Pagebuilder\Database\Seeds\ElementTableSeeder] does not exist.

**Comment by ehsantalkhouncheh** [comment]
Also after run seeds manually when i try to visit the website i faced this error`Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Language] does not exist.
`

**Comment by safrakib** [comment]
I'm facing the same issue. My Laravel version is 10.
https://prnt.sc/iwL8OYEAJkLa

**Comment by Flobbos** [comment]
What exactly are you trying to do when facing this issue?

**Comment by safrakib** [comment]
when run the php artisan pagebuilder: install command showing error Target class [Flobbos\Pagebuilder\Database\Seeds\ElementTableSeeder] does not exist.

**Comment by Flobbos** [comment]
Alright. Thanks for the details. I will take a look and get back to you as soon as I can.

**Comment by Faber44** [comment]
Still the same problem in both Laravel 9 and Laravel 10.
I have published and changed the config file "translatabledd.php" like said :
''language_model' => 'Flobbos\Pagebuilder\Models\Language'.
Same problem.
